### ISSUE TITLE
NetManager 类单例可以直接使用关键字object 修饰，不需要再添加多余代码

### ISSUE THREAD

**Issue by ZhongHaoHero666** [chenyy0708/KT#1]
objecet NetManager {
}

**Comment by chenyy0708** [comment]
驳回：详情参考https://mp.weixin.qq.com/s?__biz=MzIwMzYwMTk1NA%3D%3D&mid=2247489158&idx=1&sn=9a72afd00f16607ed673b9750278cdad

**Comment by ZhongHaoHero666** [comment]
这个博客介绍的很详细，谢谢。
